package repository

import (
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/whatacotton/tarumi/internal/config"
	"github.com/whatacotton/tarumi/internal/models"
)

func TestOAuthTokenRepository_Create(t *testing.T) {
	// Initialize test database
	config.InitDB()
	repo := NewOAuthTokenRepository() // No parameter needed

	userID := uuid.New().String() // Use pure UUID
	token := &models.OAuthToken{
		// ID is auto-generated by database, don't set it manually
		AccessToken:  "access-token-123",
		RefreshToken: "refresh-token-123",
		TokenType:    "Bearer",
		ExpiresAt:    int(time.Now().Add(time.Hour).Unix()),
	}

	err := repo.Update(token)
	if err != nil {
		t.Errorf("Failed to create token: %v", err)
	}

	// Verify token was created
	retrievedToken, err := repo.GetByUserID(userID)
	if err != nil {
		t.Errorf("Failed to retrieve token: %v", err)
	}

	if retrievedToken.AccessToken != "access-token-123" {
		t.Errorf("Expected access token 'access-token-123', got '%s'", retrievedToken.AccessToken)
	}

	// Clean up
	repo.DeleteByUserID(userID)
}

func TestOAuthTokenRepository_Update(t *testing.T) {
	config.InitDB()
	repo := NewOAuthTokenRepository() // No parameter needed

	userID := uuid.New().String() // Use pure UUID
	// Create initial token
	token := &models.OAuthToken{
		// ID is auto-generated by database
		AccessToken:  "old-token",
		RefreshToken: "refresh-token-123",
		TokenType:    "Bearer",
		ExpiresAt:    int(time.Now().Add(time.Hour).Unix()),
	}
	repo.Update(token)

	// Update token
	token.AccessToken = "new-token"
	err := repo.Update(token)
	if err != nil {
		t.Errorf("Failed to update token: %v", err)
	}

	// Verify update
	updatedToken, err := repo.GetByUserID(userID)
	if err != nil {
		t.Errorf("Failed to retrieve updated token: %v", err)
	}

	if updatedToken.AccessToken != "new-token" {
		t.Errorf("Expected access token 'new-token', got '%s'", updatedToken.AccessToken)
	}

	// Clean up
	repo.DeleteByUserID(userID)
}

func TestOAuthTokenRepository_DeleteByUserID(t *testing.T) {
	config.InitDB()
	repo := NewOAuthTokenRepository() // No parameter needed

	userID := uuid.New().String() // Use pure UUID
	// Create token
	token := &models.OAuthToken{
		// ID is auto-generated by database
		AccessToken:  "access-token-123",
		RefreshToken: "refresh-token-123",
		TokenType:    "Bearer",
		ExpiresAt:    int(time.Now().Add(time.Hour).Unix()),
	}
	repo.Update(token)

	// Delete token
	err := repo.DeleteByUserID(userID)
	if err != nil {
		t.Errorf("Failed to delete token: %v", err)
	}

	// Verify deletion
	_, err = repo.GetByUserID(userID)
	if err == nil {
		t.Error("Expected error when retrieving deleted token")
	}
}

func TestOAuthTokenRepository_IsExpired(t *testing.T) {
	config.InitDB()
	repo := NewOAuthTokenRepository() // No parameter needed

	userIDExpired := uuid.New().String() // Use pure UUID
	userIDValid := uuid.New().String()   // Use pure UUID

	// Create expired token
	expiredToken := &models.OAuthToken{
		// ID is auto-generated by database
		AccessToken:  "expired-token",
		RefreshToken: "refresh-token",
		TokenType:    "Bearer",
		ExpiresAt:    int(time.Now().Add(-time.Hour).Unix()), // Expired 1 hour ago
	}
	repo.Update(expiredToken)

	// Create valid token
	validToken := &models.OAuthToken{
		// ID is auto-generated by database
		AccessToken:  "valid-token",
		RefreshToken: "refresh-token",
		TokenType:    "Bearer",
		ExpiresAt:    int(time.Now().Add(time.Hour).Unix()), // Expires in 1 hour
	}
	repo.Update(validToken)

	// Test expired token
	expired, err := repo.IsExpired(userIDExpired)
	if err != nil {
		t.Errorf("Error checking expired token: %v", err)
	}
	if !expired {
		t.Error("Expected token to be expired")
	}

	// Test valid token
	expired, err = repo.IsExpired(userIDValid)
	if err != nil {
		t.Errorf("Error checking valid token: %v", err)
	}
	if expired {
		t.Error("Expected token to be valid")
	}

	// Clean up
	repo.DeleteByUserID(userIDExpired)
	repo.DeleteByUserID(userIDValid)
}
